-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1


# SELECT (SELECT SUM(SCORE) AS SCORE
#         FROM HR_GRADE
#         GROUP BY EMP_NO
#         ORDER BY SCORE DESC
#         LIMIT 1) AS SCORE, E.EMP_NO
# FROM HR_EMPLOYEES E